# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MenToMen_Rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mentees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Mentee')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mentees', models.ManyToManyField(through='auction.MenToMen_Rel', to='auction.Mentee')),
            ],
        ),
        migrations.AddField(
            model_name='mentomen_rel',
            name='mentors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Mentor'),
        ),
    ]
