# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import mentoring.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mentoring.utils.random_name_upload_to, verbose_name='사진 업로드'),
        ),
    ]
